site_name: Solipsse's Wiki
#site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: en
  icon:
    logo: material/book-open-page-variant
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: solipsse
      repo: wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.snippets:
  #     auto_append:
  #       - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - extra.css
extra_javascript:
  - extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js

plugins:
  - search
  - mkdocs-jupyter:
      execute: true
  # - minify:
  #     minify_html: true
  - macros
  - literate-nav
  - git-revision-date-localized
  - awesome-pages
  - mike
# nav:
#   - Home: index.md
#   - Notes:
#       - topic1.md
#       - topic2.md
#   - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/solipsse
